# Generated by Django 3.2.7 on 2022-01-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='time',
            new_name='STime',
        ),
    ]
