# Generated by Django 3.2.7 on 2022-01-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_timings_stime_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stime',
            old_name='timing',
            new_name='timings',
        ),
    ]
